language: java
sudo: false
jdk:
- oraclejdk8
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_eb0fb41b662a_key -iv $encrypted_eb0fb41b662a_iv -in gradle.properties.enc -out gradle.properties -d || true
